name: Caching Experiment

on:
  push:
    branches:
      - community-over-code
  workflow_dispatch:

env:
  MAVEN_ARGS: -Ddevelocity.url=https://ge.solutions-team.gradle.com --batch-mode --no-transfer-progress
  MAVEN_GOALS: clean verify -DskipTests
  DISABLE_MAVEN_CACHE: -Dmaven.build.cache.enabled=false
  DISABLE_DEVELOCITY_CACHE: -Ddevelocity.cache.local.enabled=false -Ddevelocity.cache.remote.enabled=false
  ENABLE_DEVELOCITY_CACHE: -Ddevelocity.cache.local.enabled=true
  ENABLE_MAVEN_CACHE: -Dmaven.build.cache.enabled=true
  DEVELOCITY_BUILD_CACHE: ~/.m2/.develocity/build-cache
  DEVELOCITY_FINGERPRINT_CACHE: ~/.m2/.develocity/fingerprint-cache
  MAVEN_BUILD_CACHE: ~/.m2/build-cache
  M2_REPOSITORY: ~/.m2/repository

jobs:
  seed-caches:
    name: Seed Caches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
#      - name: Setup Maven
#        uses: gradle/develocity-actions/maven-setup@v1
#        with:
#          develocity-access-key: ${{ secrets.GE_ACCESS_TOKEN }}
      - name: Restore Dependency Cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.M2_REPOSITORY }}
          key: m2-repository-
      - name: Restore Develocity Fingerprint Cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.DEVELOCITY_FINGERPRINT_CACHE }}
          key: dv-fingerprint-cache-
      - name: Restore Develocity Build Cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.DEVELOCITY_BUILD_CACHE }}
          key: dv-build-cache-
      - name: Build Project and Download All Dependencies
        run: ./mvnw clean dependency:go-offline ${{ env.MAVEN_GOALS }} ${{ env.ENABLE_MAVEN_CACHE }} ${{ env.ENABLE_DEVELOCITY_CACHE }}
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
      - name: Save Dependency Cache
        uses: actions/cache/save@v4
        with:
          path: ${{ env.M2_REPOSITORY }}
          key: m2-repository-${{ github.run_id }}
      - name: Save Develocity Fingerprint Cache
        uses: actions/cache/save@v4
        with:
          path: ${{ env.DEVELOCITY_FINGERPRINT_CACHE }}
          key: dv-fingerprint-cache-${{ github.run_id }}
      - name: Save Develocity Build Cache
        uses: actions/cache/save@v4
        with:
          path: ${{ env.DEVELOCITY_BUILD_CACHE }}
          key: dv-build-cache-${{ github.run_id }}
      - name: Save Maven Build Cache
        uses: actions/cache/save@v4
        with:
          path: ${{ env.MAVEN_BUILD_CACHE }}
          key: m2-build-cache-${{ github.run_id }}

#  baseline:
#    name: Baseline
#    runs-on: ubuntu-latest
#    needs: seed-caches
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#      - name: Setup Java
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'temurin'
#          java-version: '17'
#      - name: Setup Maven
#        uses: gradle/develocity-actions/maven-setup@v1
#        with:
#          develocity-access-key: ${{ secrets.GE_ACCESS_TOKEN }}
#      - name: Restore Dependency Cache
#        uses: actions/cache/restore@v4
#        with:
#          path: ${{ env.M2_REPOSITORY }}
#          key: m2-repository-
#      - name: Restore Develocity Fingerprint Cache
#        uses: actions/cache/restore@v4
#        with:
#          path: ${{ env.DEVELOCITY_FINGERPRINT_CACHE }}
#          key: dv-fingerprint-cache-
#      - name: Build Project and Download All Dependencies
#        run: ./mvnw ${{ env.MAVEN_GOALS }} ${{ env.DISABLE_MAVEN_CACHE }} ${{ env.DISABLE_DEVELOCITY_CACHE }}
