name: Caching Experiment

on:
  push:
    branches:
      - community-over-code
  workflow_dispatch:

env:
#  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3
  MAVEN_ARGS: -Ddevelocity.url=https://ge.solutions-team.gradle.com --quiet --batch-mode --no-transfer-progress
  MAVEN_GOALS: clean verify -DskipTests
  DEVELOCITY_URL: "https://ge.solutions-team.gradle.com"

jobs:
  seed-dependency-cache:
    name: Seed Dependency Cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Maven
        uses: gradle/develocity-actions/maven-setup@v1
        with:
          develocity-access-key: ${{ secrets.GE_ACCESS_TOKEN }}
      - name: Restore Dependency Cache
        uses: actions/cache/restore@v4
        with:
          path: ~/.m2/repository
          key: m2-repository-${{ hashFiles('**/pom.xml') }}-
      - name: Seed Dependency Cache
        run: ./mvnw dependency:go-offline
      - name: Save Dependency Cache
        uses: actions/cache/save@v4
        with:
          path: ~/.m2/repository
          key: m2-repository-${{ hashFiles('**/pom.xml') }}-${{ github.run_id }}

#  baseline:
#    name: Baseline
#    runs-on: ubuntu-latest
#    needs: seed-dependency-cache
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#      - name: Setup Maven
#        uses: gradle/develocity-actions/maven-setup@v1
#        with:
#          develocity-access-key: ${{ env.DEVELOCITY_ACCESS_KEY }}
#      - name: Restore Dependency Cache
#        uses: actions/cache/restore@v4
#        with:
#          path: ~/.m2/repository
#          key: m2-repository-${{ hashFiles('**/pom.xml') }}-
#      - name: Build
#        run: ./mvnw ${{ env.MAVEN_GOALS }}